### ISSUE TITLE
Token should be refreshed before timeout.

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#107]
To prevent the token timeout (1h - 2h), we should refresh the token with `setInterval`.

**Comment by kamataryo** [comment]
1. fetch new sources
2. `getStyle`
3. set new params

**Comment by miya0001** [comment]
あっ、定期的にタイルだけリフレッシュしてるっぽい。

> options.refreshExpiredTiles

https://docs.mapbox.com/mapbox-gl-js/api/

**Comment by kamataryo** [comment]
なるほど、長時間待つと領域内であっても白くなってるのはこのせいですね。

**Comment by miya0001** [comment]
`options.transformRequest` を使った方法を検討したほうがいいかも。

* https://docs.mapbox.com/mapbox-gl-js/api/#map
* https://docs.mapbox.com/mapbox-gl-js/api/#requestparameters

**Comment by kamataryo** [comment]
#172 で実装済みと言う認識 @keichan34 👍
