### ISSUE TITLE
script タグの取得方法の改善

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#128]
現状:
- `document.getElementsByTagName` で `<script />` を探している
良さそう:
- `<script id="geolonia-script" />` のような ID を振り `document.getElementById` で取得する

TODO:
- 計算量などを検討する
- 後者に変更するメリットがあると判断できた場合、仕様を変更して後者を採用。その際後方互換を維持するため、IDが見つからなかった場合に前者の方法をフォールバックとして用いる

**Comment by miya0001** [comment]
Closed by #130 #131
