### ISSUE TITLE
HTMLElement の ID と geolonia クラスを併用すると不具合がある

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#169]
以下のようにすると `map` インスタンスが意図通り動かないケースがある。

```html
<div id="map" class="geolonia"></div>
<script>
const map = new window.geolonia.Map("#map")
</script>
```

`#map` と `.geolonia` に対しておそらく2つの `Map` インスタンスが作られていて、 `HTMLElement` がどちらに紐づいているかが環境によって違ってくるのかもしれない。
不具合が発生しているケースでは、例えば `marker.addTo(map)` としても表示されなかったりする。

**Comment by miya0001** [comment]
Closed by #171
