### ISSUE TITLE
Geolocation Control や Navigation Controlなどを右下に移動するオプションが欲しい

### ISSUE THREAD

**Issue by naogify** [geolonia/embed#191]
スマートフォンで操作時に `Geolocation Control` や `Navigation Control` が右上にあると指が届きにくいので、左下に移動させるオプションが欲しい。

デフォルトは `right-top` で、 `right-bottom` を指定できると良い。

**Comment by naogify** [comment]
ユーザーエージェントで、`right-top` と `right-bottom`を自動で切り替えるかは迷うところ。

**Comment by kamataryo** [comment]
関連 #189
