### ISSUE TITLE
data-simple-vector の API キー

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#217]
`data-simple-vector` と `<script>` で両方指定するのは冗長なので、 script から取得した API キーをデフォルトにできないか？

**Comment by keichan34** [comment]
@kamataryo おそらく、こちらでkeyを設定しているので、両方指定する必要が無いんじゃないかな。。？

https://github.com/geolonia/embed/blob/master/src/lib/geolonia-map.js#L82-L89

tileserver-dev.geolonia.com の場合は指定する必要あるかもしれないんですが。。tileserver-dev も追加しましょうか？

**Comment by kamataryo** [comment]
あ、了解です。 dev でやったら403になったので、dev 環境の場合もキーを送れると良さそうです！
