### ISSUE TITLE
data-geolonia-control="top-left" 時に、ロゴが上に張り付き状態

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/embed#224]
![スクリーンショット 2021-08-05 0 57 18](https://user-images.githubusercontent.com/1124652/128213938-4548d83d-eab3-4c50-8793-6d90a007f408.png)

**Comment by ShinichiNishikawa** [comment]
よく見ると右上のナビゲーションコントロールもですね。

**Comment by ShinichiNishikawa** [comment]
失礼！

bottom-leftでも同じでした。右上のナビゲーションあたりにパディング的なものがない。

![スクリーンショット 2021-08-05 1 07 32](https://user-images.githubusercontent.com/1124652/128215465-0e307681-1d02-4899-9920-3cc2d1522857.png)

**Comment by kamataryo** [comment]
こちら、問題ないように調整しているはず..。調査します。
確認用のデモの GitHub Pages: https://geolonia.github.io/embed/controls

**Comment by keichan34** [comment]
<img width="1178" alt="Screen Shot 2021-08-06 at 10 22 33" src="https://user-images.githubusercontent.com/1064513/128441714-06d7d81b-077a-4d31-aefc-7559fb6e84f7.png">

**Comment by kamataryo** [comment]
こちら、クローズします。ディスカッションは #226 で継続。

@ShinichiNishikawa 当該ページでは `.post_content>:first_child` の `marigin-top: 0! important;` という CSS が干渉しているので、こちらを解消していただけますと。

**Comment by kamataryo** [comment]
FYI. 上記の CSS は swell 由来です。
