### ISSUE TITLE
mbtiles の直接アップロード時の Simple Style 関係の挙動について確認

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#231]

**Comment by keichan34** [comment]
`g-simplestyle-v1` というレイヤーに入れると表示されるはず

**Comment by kamataryo** [comment]
メモ: csv/geojson をアップロードしたケースでは、 Geolonia のタイル生成時に専用のレイヤーが作成されるため SimpleStyle が適用される。一方 MBTiles はレイヤーを加工しないので、SimpleStyle が表示されるかどうかは完全にユーザー依存。

**Comment by kamataryo** [comment]
<img width="980" alt="スクリーンショット 2021-08-24 16 21 25" src="https://user-images.githubusercontent.com/6292312/130574231-611faee1-b1f2-4c72-89c6-e4dcf6a36af0.png">
