### ISSUE TITLE
グローバルスコープのプロパティの互換性について (mapboxgl と maplibregl)

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#248]
dev 環境にデプロイされているバージョンでは `window.mapboxgl.Map` -> `window.maplibregl.Map` となっているので、`window.mapboxgl` を使っているユーザーは地図が表示されなくなります。

`window.mapboxgl` も残すのはいかがでしょう？

**Comment by keichan34** [comment]
あ、そうですね、 window.mapboxgl = window.maplibregl にしましょう。
maplibregl 2.x にアップグレードする時に、embed api v2 として新しいバージョンをリリースしなければならないような気がする。。maplibregl 2.x の状況を様子見ながら進みましょうか

**Comment by kamataryo** [comment]
https://github.com/geolonia/embed/pull/249
