### ISSUE TITLE
カスタムアイコンを使用した場合、最大化しないと消失してしまうマーカーが存在する

### ISSUE THREAD

**Issue by champierre** [geolonia/embed#331]
https://gyazo.com/9dcde491280c5684dd5c8d2a4afdc272?fbclid=IwAR3QnhPqkySlu53LFb1kLS0VGj5_AW5kPmu8ovRGaHd4ILgRAk42rsdUKbI

**Comment by keichan34** [comment]
これはクラストリングのradiusがアイコンのradiusと合ってないからなのかな、、。やはり、allow overlapを有効にしたりした方がいいのか、何かしらのアイコンのサイズを認識する仕組みを考えるとか。。
