### ISSUE TITLE
localIdeographFontFamily: 'sans-serif' を有効化する

### ISSUE THREAD

**Issue by naogify** [geolonia/embed#359]
localIdeographFontFamily を無効化したことにより、フォントのダウンロード時間が増え地図の表示が遅くなっているので、再度有効化したい。

Google Chrome の開発者ツールで、「キャッシュを無効化」し、ネットワークを「高速3G」に設定して、maps.geolonia.com を表示してして調べた所、地図の表示までに 約90秒かかり、7.39秒以降は全てフォントをダウンロードしている時間だったので、ローカルフォントを使用することで、表示を高速化したい。

![スクリーンショット 2023-05-29 22 08 27](https://github.com/geolonia/embed/assets/8760841/b35d43f0-486f-4c56-b4ef-ae3b9efe99c8)

**Comment by keichan34** [comment]
背景

* https://github.com/geolonia/embed/pull/351
* https://github.com/geoloniamaps/basic-v1/issues/14
