### ISSUE TITLE
publicPathの追加によりマーカークリック時にChunkLoadErrorが発生する

### ISSUE THREAD

**Issue by shoko93** [geolonia/embed#379]
v4.1.0に変更されてからマーカーをクリックした際にChunkLoadErrorが発生するようになりました。マーカーの表示にはGeoJSONを使用しています。
こちらのCodePenのサンプルで「集合場所」をクリックしたときにエラーを再現できます。
https://codepen.io/geolonia/pen/qBdoWLL

v4.0.0のソースコードでは発生せず、ローカル環境で検証したところ今回のバージョンアップで追加されたpublicPathをコメントアウトすると正常に動くことが確認できました。

お手数ですがご確認の程よろしくお願いいたします。

**Comment by keichan34** [comment]
@shoko93 Geolonia Maps 利用いただきありがとうございました！こちらの不具合の修正を先程リリースしましたので、ご確認いただけばと思います。

**Comment by shoko93** [comment]
@keichan34 
早速のご対応ありがとうざいました！修正確認しました。
